# Generated by Django 6.0.3 on 2026-03-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_familymember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='email',
        ),
        migrations.AddField(
            model_name='familymember',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familymember',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3),
        ),
        migrations.CreateModel(
            name='FamilyMemberFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='family_files/')),
                ('description', models.TextField()),
                ('family_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.familymember')),
            ],
        ),
    ]
