# Generated by Django 6.0.3 on 2026-03-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_familymember_email_familymember_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='nationality',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
