# Generated by Django 6.0.3 on 2026-03-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_familymember_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AddField(
            model_name='familymember',
            name='relation',
            field=models.CharField(default='Self', max_length=50),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=10),
        ),
    ]
