# Generated by Django 6.0.3 on 2026-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_familymember_gender_familymember_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='family_profiles/'),
        ),
    ]
