# Generated by Django 6.0.3 on 2026-03-27 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_familymember_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
