# Generated by Django 6.0.3 on 2026-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_familymember_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
