# Generated by Django 6.0.3 on 2026-03-27 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_familymember_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familymember',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='familymemberfile',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
