# Generated by Django 6.0.3 on 2026-03-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_familymember_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymemberfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
